### ISSUE TITLE
Bot para AlgoritmiaUNO

### ISSUE THREAD

**Issue by IgnaGarcia** [gnuno/brainstorming#5]
Un bot que este al pendiente del repositorio gnuno/algoritmia y notifique por telegram:

- En un principio cuando hay pullrequest
- Si prospera, cuando haya un nuevo desafio muestre el readme(y si es posible pinee el mensaje)

**Comment by matiasnoriega** [comment]
Menos de un mes y ya tenemos el bot andando, felicitaciones @IgnaGarcia !

Cierro el Issue.
